name = "rc-sumo-server"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "RoomDO" }
]

# ВАЖЛИВО: у тебе на сервері вже існує tag v2, тому ми його явно вказуємо
[[migrations]]
tag = "v2"
new_sqlite_classes = ["RoomDO"]
